### ISSUE TITLE
Exception with PDFs

### ISSUE THREAD

**Issue by mbastian** [pprados/langchain-googledrive#3]
Hi, and thank you for this great piece of work extending the GDrive features.

My use-case is a drop-in replacement for the default loader as I have some Google Slides content. Unfortunately, I also have PDF files and I see that this library changes how PDFs are dealt compared to the default loader. In my case, it breaks with the following error:
`Exception during the conversion of file 'XXX.pdf' (cannot import name 'PDFResourceManager' from 'pdfminer.converter'`

Besides giving a clue about this issue, I was curious what motivated changing the approach with PDFs? Greetings,

**Comment by pprados** [comment]
The implementation proposes to use a dictionary to associate a [mime-type to a loader](https://github.com/pprados/langchain-googledrive/blob/master/langchain_googledrive/utilities/google_drive.py#L168).

It's possible to change these dictionaries with the parameter `conv_mapping` (See [here](https://github.com/pprados/langchain-googledrive/blob/master/langchain_googledrive/utilities/google_drive.py#L549).

You can choose whatever you want to read pdf.
I use UnstructuredPDFLoader, because the loader can be shared with others files formats.

**Comment by mbastian** [comment]
Sounds good, thanks for the clarification 👍
